mbsbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  

  # Velocity Controllers ---------------------------------------
  left_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController 
    joint: rl_axis
    pid: {p: 8, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: rr_axis
    pid: {p: 8, i: 0.0, d: 0.0, i_clamp: 0.0}
  left_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: fl_axis
    pid: {p: 8, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: fr_axis
    pid: {p: 8, i: 0.0, d: 0.0, i_clamp: 0.0}


  # Position Controllers ---------------------------------------
  left_steering_hinge_position_controller:
    joint: lstr_joint
    type: effort_controllers/JointPositionController
    pid: {p: 100.0, i: 0.0, d: 10}
  right_steering_hinge_position_controller:
    joint: rstr_joint
    type: effort_controllers/JointPositionController
    pid: {p: 100.0, i: 0.0, d: 10}

