zebrat:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30
  

  # Velocity Controllers ---------------------------------------
  left_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController 
    joint: rl_axle
    pid: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: rr_axle
    pid: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  left_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: fl_axle
    pid: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: fr_axle
    pid: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}


  # Position Controllers ---------------------------------------
  left_steering_hinge_position_controller:
    joint: base2lstr
    type: effort_controllers/JointPositionController
    pid: {p: 50.0, i: 0.0, d: 10.0}
  right_steering_hinge_position_controller:
    joint: base2rstr
    type: effort_controllers/JointPositionController
    pid: {p: 50.0, i: 0.0, d: 10.0}

